"""Fachada de servicios para expediente clínico único y contexto longitudinal."""

from app.services.expediente_flow import ver_expediente_flow
from app.services.expediente_plus_flow import (
    EXPEDIENTE_COHORTES,
    EXPEDIENTE_GENOMICA,
    build_completitud_index,
    build_fhir_careplans,
    build_fhir_goals,
    build_fhir_medication_requests,
    ensure_default_rule,
    ensure_expediente_plus_schema,
    export_enriched_dataset,
    get_active_rules,
    get_enriched_by_consulta_id,
    ingest_offline_payload,
    list_cohorts,
    log_expediente_access,
    run_cohort,
    save_cohort,
    summarize_access_audit,
    upsert_enriched_record,
)
from app.services.expediente_nota_medica_flow import (
    EXPEDIENTE_NOTAS_DIARIAS,
    NOTA_MEDICA_SERVICIOS,
    ensure_expediente_nota_schema,
    get_active_hospitalizacion_for_profile,
    get_cie10_catalog,
    get_labs_for_profile_date,
    resolve_profile_identity,
    save_nota_medica_diaria,
)
from app.services.master_identity_flow import (
    PATIENT_IDENTITY_EVENTS,
    PATIENT_IDENTITY_LINKS,
    PATIENT_MASTER_IDENTITY,
    backfill_master_identity,
    ensure_master_identity_schema,
    get_master_identity_journey,
    get_master_identity_snapshot,
    list_master_identity_conflicts,
    master_identity_operational_stats,
    resolve_master_identity_conflict,
)

__all__ = [
    "EXPEDIENTE_COHORTES",
    "EXPEDIENTE_GENOMICA",
    "EXPEDIENTE_NOTAS_DIARIAS",
    "NOTA_MEDICA_SERVICIOS",
    "PATIENT_IDENTITY_EVENTS",
    "PATIENT_IDENTITY_LINKS",
    "PATIENT_MASTER_IDENTITY",
    "backfill_master_identity",
    "build_completitud_index",
    "build_fhir_careplans",
    "build_fhir_goals",
    "build_fhir_medication_requests",
    "ensure_default_rule",
    "ensure_expediente_nota_schema",
    "ensure_expediente_plus_schema",
    "ensure_master_identity_schema",
    "export_enriched_dataset",
    "get_active_hospitalizacion_for_profile",
    "get_active_rules",
    "get_cie10_catalog",
    "get_enriched_by_consulta_id",
    "get_labs_for_profile_date",
    "get_master_identity_journey",
    "get_master_identity_snapshot",
    "ingest_offline_payload",
    "list_cohorts",
    "list_master_identity_conflicts",
    "log_expediente_access",
    "master_identity_operational_stats",
    "resolve_master_identity_conflict",
    "resolve_profile_identity",
    "run_cohort",
    "save_cohort",
    "save_nota_medica_diaria",
    "summarize_access_audit",
    "upsert_enriched_record",
    "ver_expediente_flow",
]
