from __future__ import annotations

from app.core.boot_profile import BOOT_PROFILE_JEFATURA_UROLOGIA, BOOT_PROFILE_RESIDENTES_UROLOGIA

JEFATURAS_ROUTER_MODULE_IDS = frozenset({"jefaturas"})
JEFATURAS_BOOT_PROFILES = frozenset({BOOT_PROFILE_JEFATURA_UROLOGIA, BOOT_PROFILE_RESIDENTES_UROLOGIA})
